# Generated by Django 3.0.3 on 2020-06-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_code', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=50)),
                ('account_bal', models.IntegerField(default=0)),
                ('bill', models.IntegerField(default=0)),
                ('advance', models.IntegerField(default=0)),
            ],
        ),
    ]
